jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      NODE_VERSION: 12.13.1
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
      NG_CLI_ANALYTICS: 'false'

    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - task: NodeTool@0
        inputs:
          versionSpec: '12.13.1'
        displayName: 'TOOLS: install Node.js'
      - script: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          export PATH=$HOME/.yarn/bin:$PATH
        displayName: 'TOOLS: install Yarn'
      - script: sudo /etc/init.d/mysql stop
        displayName: 'TOOLS: stop MySQL'
      #----------------------------------------------------------------------
      # Tests
      #----------------------------------------------------------------------
      - script: yarn install
        displayName: 'INSTALL: launch yarn install'
      - script: yarn test
        displayName: 'TESTS: frontend'
